[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = [
	"E", # pycodestyle
	"F", # pyflakes
	"I", # isort
	"B", #flake8-bugbear
]
fixable = [
	"I", # for safety reasons we will only fix isort, and lint the other rules
]