name: Terraform Apply - Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Apply Terraform Changes
        run: |
          terraform -chdir=terraform apply -auto-approve
