LGBMClassifier:
  base_trials:
    default:
      boosting_type: "gbdt"
      objective: "binary"
      metric: "auc"
      learning_rate: 0.1
      num_leaves: 31
      max_depth: -1 
      n_estimators: 1000
      min_data_in_leaf: 20
      min_sum_hessian_in_leaf: 1.e-3
      bagging_fraction: 1.0
      reg_alpha: 0.0
      reg_lambda: 0.0
      subsample_freq: 0
      feature_fraction: 1.0
      feature_fraction_bynode: 1.0
      max_delta_step: 0.0
      max_bin: 255
    best_found:
      boosting_type: 'gbdt'
      objective: 'binary'
      metric: 'auc'
      learning_rate: 0.08767009868144243
      num_leaves: 59
      max_depth: 20
      n_estimators: 1000
      min_data_in_leaf: 7
      min_sum_hessian_in_leaf: 6.466597430997204
      bagging_fraction: 0.547070560433649
      reg_alpha: 13.224033076660836
      reg_lambda: 76.05355706430626
      subsample_freq: 0
      feature_fraction: 0.8248602702109634
      feature_fraction_bynode: 0.9211547910665975
      max_delta_step: 9.626202028426249
      max_bin: 255
  grid:
    boosting_type: ["gbdt", "rf"]
    objective: ["binary"]
    metric: ["auc"]
    learning_rate: [1.e-5, 0.1]
    num_leaves: [2, 64]
    max_depth: [-1, 20]
    n_estimators: [1000, 1000]
    min_data_in_leaf: [1, 40]
    min_sum_hessian_in_leaf: [1.e-5, 10]
    bagging_fraction: [0.5, 1.0]
    reg_alpha: [0.0, 100]
    reg_lambda: [0.0, 100]
    subsample_freq: [0, 10]
    feature_fraction: [0.8, 1.0]
    feature_fraction_bynode: [0.8, 1.0]
    max_delta_step: [0.0, 10.0]
    max_bin: [255, 255]



CatBoostClassifier:
  base_trials:
    default:
      n_estimators: 100
      nan_mode: 'Min'
      sampling_frequency: 'PerTree'
      leaf_estimation_method: 'Newton'
      random_score_type: 'NormalWithModelSizeDecrease'
      grow_policy: 'SymmetricTree'
      penalties_coefficient: 1
      boosting_type: 'Plain'
      model_shrink_mode: 'Constant'
      feature_border_type: 'GreedyLogSum'
      l2_leaf_reg: 3
      random_strength: 1
      rsm: 1
      subsample: 0.800000011920929
      random_seed: 42
      depth: 6
      posterior_sampling: False
      model_shrink_rate: 0
      learning_rate: 0.0637660026550293
      #score_function: 'Cosine'
      bootstrap_type: 'MVS'
      max_leaves: 64
      auto_class_weights: "Balanced"
  grid:
    n_estimators: [1000, 1000]
    learning_rate: [1.e-5, 3.e-1]
    auto_class_weights: ["Balanced", "SqrtBalanced"]
    grow_policy: ['SymmetricTree']
    random_score_type: ["Gumbel", "NormalWithModelSizeDecrease"]
    penalties_coefficient: [0.5, 2.0]
    depth: [5, 10]
    l2_leaf_reg: [1.e-5, 100]
    subsample: [0.8, 1]
    bootstrap_type: ["MVS", "Bernoulli"]
    leaf_estimation_method: ["Newton", "Gradient"]
    sampling_frequency: ["PerTree", "PerTreeLevel"]
    boosting_type: ["Plain", "Ordered"]
    model_shrink_mode: ["Constant", "Decreasing"]
    feature_border_type: ["GreedyLogSum", "Median", "Uniform", "MinEntropy"]
    # posterior_sampling: [true, false] # TODO: Parse booleans in tuning
    #score_function: ["Cosine", "L2"]
    random_strength: [0.5, 2]
    #model_shrink_rate: [0, 0.9]
    rsm: [0.1, 1]

XGBClassifier:
  base_trials:
    default:
      n_estimators: 1000
      learning_rate: 0.299
      max_depth: 6
      reg_alpha: 0
      reg_lambda: 1
      subsample: 1
  grid:
    n_estimators: [500,2000]
    learning_rate: [1.e-5, 0.3]
    max_depth: [1, 16]
    reg_alpha: [1.e-5, 100]
    reg_lambda: [1.e-5, 100]
    subsample: [0.8, 1]
    colsample_bytree: [0.1, 1]
    colsample_bylevel: [0.1, 1] 
    colsample_bynode: [0.1, 1]
    gamma: [0.01, 1.0]
    min_child_weight: [0.01, 10.0]
    