name: Terraform Apply - Dev Branch

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ init

      - name: Apply Terraform Changes
        run: |
          terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ apply -auto-approve
