name: Terraform Apply - Dev Branch

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ml-projects-399119

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ init

      - name: Apply Terraform Changes
        run: |
          terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ apply
