name: Terraform Apply - Dev Branch

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2
        with:
          version: 'latest'  # You can specify a specific version if neededa
          project_id: ml-projects-399119

      - name: Authenticate with gcloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > /tmp/gcp_sa_key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json

      - name: Initialize Terraform
        run: terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ init

      - name: Apply Terraform Changes
        run: |
          terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ apply
