name: Terraform Apply - Dev Branch

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Initialize Terraform
        run: terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ init

      - name: Apply Terraform Changes
        run: |
          terraform -chdir=\{\{\ cookiecutter.project_name\ \}\}/terraform/ apply
